name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -cover -v

    - name: Bench multi-thread
      run: go test -bench .

    - name: Bench single-thread
      run: GOMAXPROCS=1 go test -bench .

    - name: Bench multi-thread with race detection
      run: go test -race -bench .
